// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR-FWtqhzi9nvJg0NBTrTaOuv7yr38T0Y',
    appId: '1:125320758727:web:12b8641ba8098eda4dc5e2',
    messagingSenderId: '125320758727',
    projectId: 'city-guide-d829b',
    authDomain: 'city-guide-d829b.firebaseapp.com',
    storageBucket: 'city-guide-d829b.firebasestorage.app',
    measurementId: 'G-2T2VTSVSM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGb94XmmgO6pUgZ2mKH6HYnIIlxnU00vY',
    appId: '1:125320758727:android:a800c9d42b80f9604dc5e2',
    messagingSenderId: '125320758727',
    projectId: 'city-guide-d829b',
    storageBucket: 'city-guide-d829b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyJN86kcDKM1ptg0D-ipezqSapQa-UJB0',
    appId: '1:125320758727:ios:0e2a3844c57a15a34dc5e2',
    messagingSenderId: '125320758727',
    projectId: 'city-guide-d829b',
    storageBucket: 'city-guide-d829b.firebasestorage.app',
    iosBundleId: 'com.example.work',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyJN86kcDKM1ptg0D-ipezqSapQa-UJB0',
    appId: '1:125320758727:ios:0e2a3844c57a15a34dc5e2',
    messagingSenderId: '125320758727',
    projectId: 'city-guide-d829b',
    storageBucket: 'city-guide-d829b.firebasestorage.app',
    iosBundleId: 'com.example.work',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR-FWtqhzi9nvJg0NBTrTaOuv7yr38T0Y',
    appId: '1:125320758727:web:72cf1d9d86be95324dc5e2',
    messagingSenderId: '125320758727',
    projectId: 'city-guide-d829b',
    authDomain: 'city-guide-d829b.firebaseapp.com',
    storageBucket: 'city-guide-d829b.firebasestorage.app',
    measurementId: 'G-X9SBZ4H7N4',
  );
}
